@startuml
'https://plantuml.com/class-diagram

enum Tipus{
FOC
AIGUA
PLANTA
TERRA
ACER
BESTIOLA
DRAC
ELÈCTRIC
FANTASMA
FADA
GEL
LLUITA
PLANTA
PSÍQUIC
ROCA
SINISTRE
VERÍ
VOLADOR
}

class Cartes{
---Atributs---
    - Tipus: enum
    - PuntsAtac: Int
    - PuntDefensa: Int
---Metodes---
 + consultarNomCarta()
 +
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml